<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Machine_Learning/blob/main/MultipleLinearRegression_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded=files.upload()

Saving 1.02.+Multiple+linear+regression (1).csv to 1.02.+Multiple+linear+regression (1).csv


In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression
from sklearn.preprocessing import StandardScaler

In [5]:
data= pd.read_csv("1.02.+Multiple+linear+regression (1).csv")
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [6]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   SAT         84 non-null     int64  
 1   Rand 1,2,3  84 non-null     int64  
 2   GPA         84 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 2.1 KB


In [29]:
y= data['GPA']
x1= data[['SAT','Rand 1,2,3']]

In [30]:
y.shape

(84,)

In [25]:
x1.shape

(84, 2)

Standardization

In [28]:
scaler= StandardScaler()
scaler.fit(x1)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [32]:
x=scaler.transform(x1)
x

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [33]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
reg.score(x,y)

0.4066811952814283

In [35]:
reg.intercept_

3.330238095238095

In [36]:
reg.coef_

array([ 0.17181389, -0.00703007])

Feature Selection

In [37]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [38]:
p_values= f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [39]:
p_values.round(3)

array([0.   , 0.676])

Prediction with standardized coefficient

In [40]:
new_data=pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [41]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

In [42]:
new_data_scaled=scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [44]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])