<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Machine_Learning/blob/main/TrainTestSplitLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

Generate some data we are going to split

In [3]:
a= np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b= np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

Split the data

In [5]:
train_test_split(a)

[array([49, 47, 71, 50, 60, 28,  2, 34, 95, 73, 58, 26, 40,  5, 46, 48, 98,
        94, 68, 84, 30, 93,  9,  7, 22,  3, 90, 86, 42, 38, 21, 78, 89, 55,
        99, 51,  8, 85, 57, 74, 31, 97, 59, 54, 62, 66, 20, 15, 96, 77, 12,
        33, 41, 32, 92, 83, 70, 79, 37, 24, 19, 44, 61, 91, 88,  6, 16, 14,
        45, 53,  1, 69, 65, 76, 52]),
 array([ 56,   4,  72,  17,  25,  64,  36,  75,  81,  10,  67,  63,  13,
         80,  23,  27,  82,  43, 100,  11,  18,  39,  87,  35,  29])]

In [15]:
a_train,a_test,b_train,b_test=train_test_split(a,b, test_size=0.2,random_state=365)

Explore the result

In [12]:
a_train.shape,a_test.shape

((80,), (20,))

In [13]:
a_train

array([ 18,  25,  31,  61,   7,  16,  85,  83,  49,  72,  51,  79,  17,
        57,  64,  94,  15,  86,   8,   3,  11,  50,  10,  88,  12,  74,
        20,  58,  39,  87,  13,  23,  28,  47,   9,  35,  80,  54,  69,
        66,  32,  59,  90,  41,  43,  67,  53,  27,  33, 100,  70,  62,
        48,  40,  98,  78,  97,  24,  56,  93,  34,  36,  96,  65,  76,
        45,  37,  99,  77,  60,  84,   1,  22,  82,  95,  21,  42,  26,
         6,  75])

In [14]:
a_test

array([55, 30, 89,  4, 46, 73, 29, 19, 71, 14,  2, 68, 91, 52, 63, 92,  5,
       38, 44, 81])

In [16]:
b_train.shape,b_test.shape

((80,), (20,))

In [17]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [18]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])